image: python:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  - build
  - test

build-release:
  stage: build
  script:
    - python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist
    expire_in: 7 days

test-release:
  stage: test
  script:
    - python3 -m pip install dist/hopsy* && python3 -m hopsy.test
  # TODO add test-reports