image: ubuntu:20.04 
#image: python:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build-release:
  stage: build
  before_script:
    - apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq cmake ninja-build python3 python3-pip
  script:
    - python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist
    expire_in: 7 days

test-release:
  stage: test
  before_script:
    - apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq python3 python3-pip
  script:
    - python3 -m pip install dist/hopsy*
    - ldd $(python3 -m pip show -f hopsy | grep Location | cut -f 2 -d' ')/hopsy/core.*
    - python3 -m unittest -v hopsy.tests
  # TODO add test-reports

