image: quay.io/pypa/manylinux2014_x86_64

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build-release:
  stage: build
  script:
    - for PY in "cp36-cp36m" "cp37-cp37m" "cp38-cp38" "cp39-cp39"; do /opt/python/$PY/bin/pip wheel --no-deps . -w dist; done
    - VERSION=$(cat .version); for PY in "cp36-cp36m" "cp37-cp37m" "cp38-cp38" "cp39-cp39"; do auditwheel repair dist/hopsy-$VERSION-$PY-* -w dist; done
  artifacts:
    paths:
      - dist
    expire_in: 7 days

test-release:
  stage: test
  script:
    - VERSION=$(cat .version); for PY in "cp36-cp36m" "cp37-cp37m" "cp38-cp38" "cp39-cp39"; do /opt/python/$PY/bin/python -m pip install dist/hopsy-$VERSION-$PY-manylinux*.whl; done
    - VERSION=$(cat .version); for PY in "cp36-cp36m" "cp37-cp37m" "cp38-cp38" "cp39-cp39"; do /opt/python/$PY/bin/python -m unittest -v hopsy.tests; done

