image: quay.io/pypa/manylinux2014_x86_64

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - upload-artifacts

pre-commit:
  image: python:3.10
  stage: build
  script:
    - pip install pre-commit
    - pre-commit install
    - pre-commit run --all


build-release:
  stage: build
  script:
    - /opt/python/cp310-cp310/bin/python .check_version.py
    - git rev-parse --short HEAD > .commit
    - for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/pip wheel --no-deps . -w dist; done
    - VERSION=$(cat .version); for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do auditwheel repair dist/hopsy-$VERSION-$PY-* -w dist; done
  artifacts:
    paths:
      - dist/*manylinux*
    expire_in: 7 days

build-debug:
  stage: build
  script:
    - /opt/python/cp310-cp310/bin/python .check_version.py
    - git rev-parse --short HEAD > .commit
    - echo "$(cat .version).dev0" > .version
    - sed -i 's/debug = 0/debug = 1/g' setup.cfg
    - for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/pip wheel --no-deps . -w dist; done
    - VERSION=$(cat .version); for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do auditwheel repair dist/hopsy-$VERSION-$PY-* -w dist; done
  artifacts:
    paths:
      - dist/*manylinux*
    expire_in: 7 days


test-release:
  stage: test
  before_script:
    - for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/python -m pip install docov; done
  script:
    - git rm docs/* -rf # remove old docs so no stales files remain
    - VERSION=$(cat .version); for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/python -m pip install dist/hopsy-$VERSION-$PY-manylinux*.whl; done
    - VERSION=$(cat .version); for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/python -m unittest -v tests; done
    # build docs
    - /opt/python/cp310-cp310/bin/python -m pip install sphinx pybind11 numpy pandas matplotlib  sphinx-rtd-theme  nbsphinx pydata_sphinx_theme --force-reinstall
    - cd docs-sources && /opt/python/cp310-cp310/bin/python -m sphinx -b html -d _build/doctrees   . _build/html && cp _build/* ../docs/* && cd -
    - /opt/python/cp39-cp39/bin/docov hopsy --output docs/; cat docs/docov.txt
  artifacts:
    paths:
      - docs
    expire_in: 7 days


test-debug:
  stage: test
  before_script:
    - for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/python -m pip install docov; done
  script:
    - VERSION="$(cat .version).dev0"; for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/python -m pip install dist/hopsy-$VERSION-$PY-manylinux*.whl; done
    - VERSION="$(cat .version).dev0"; for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/python -m unittest -v tests; done

  artifacts:
    paths:
      - docs
    expire_in: 7 days


upload-docs:
  stage: upload-artifacts
  only:
    - develop
    - main
    - master
  dependencies:
    - test-release
  script:
    - git config user.email $GITLAB_USER_EMAIL
    - git config user.name "CI_BOT"
    - git add docs
    - git commit -m "${CI_COMMIT_DESCRIPTION} + docs" --no-verify  || true
    - git remote remove origin || true
    - git remote add origin https://oauth2:${CI_BOT}@jugit.fz-juelich.de/IBG-1/ModSim/hopsy.git || true
    - git push origin HEAD:$CI_COMMIT_BRANCH -o ci.skip ||true # prevent triggering pipeline again
