image: quay.io/pypa/manylinux2014_x86_64
#image: ubuntu:20.04 
#image: python:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build-release:
  stage: build
    #before_script:
    #  - apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq cmake ninja-build python3 python3-pip
  script:
    #- for PY in "cp36-cp36m" "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/pip wheel --no-deps; done
    - for PY in "cp36-cp36m" "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/python setup.py bdist_wheel; done
    - VERSION=$(cat .version); for PY in "cp36-cp36m" "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do auditwheel repair /dist/hopsy-$VERSION-$PY-* -w dist; done
  artifacts:
    paths:
      - dist
    expire_in: 7 days

test-release:
  stage: test
    #before_script:
    #  - apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq python3 python3-pip
  script:
    - VERSION=$(cat .version); for PY in "cp36-cp36m" "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/python -m pip install dist/hopsy-$VERSION-$PY-manylinux*.whl -w dist; done
    - VERSION=$(cat .version); for PY in "cp36-cp36m" "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/python -m unittest -v hopsy.tests -w dist; done

