#image: ubuntu:20.04 
image: python:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build-release:
  stage: build
  tags:
    - sonic
  before_script:
    #- apt-get update -qq && apt-get install -y -qq cmake ninja-build
    - ubuntu2004
    - apt-get update
    - apt-get install -y -qq cmake ninja-build
  script:
    - python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist
    expire_in: 7 days

test-release:
  stage: test
  tags:
    - sonic
  script:
    - python3 -m pip install dist/hopsy* && python3 -m hopsy.test
  # TODO add test-reports

