image: ubuntu:20.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  - build
  - test

build-release:
  stage: build
  script:
    - python setup.py bdist_wheel
  artifacts:
    paths:
      - dist
    expire_in: 7 days

test-release:
  stage: test
  script:
    - python -m pip install dist/hopsy* && python -m hopsy.test
  # TODO add test-reports