image: quay.io/pypa/manylinux2014_x86_64

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build-release:
  stage: build
  script:
    - git rev-parse --short HEAD > .commit
    - for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/pip wheel --no-deps . -w dist; done
    - VERSION=$(cat .version); for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do auditwheel repair dist/hopsy-$VERSION-$PY-* -w dist; done
  artifacts:
    paths:
      - dist/*manylinux*
    expire_in: 7 days

build-debug:
  stage: build
  script:
    - git rev-parse --short HEAD > .commit
    - echo "$(cat .version).dev0" > .version
    - sed -i 's/debug = 0/debug = 1/g' setup.cfg
    - for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/pip wheel --no-deps . -w dist; done
    - VERSION=$(cat .version); for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do auditwheel repair dist/hopsy-$VERSION-$PY-* -w dist; done
  artifacts:
    paths:
      - dist/*manylinux*
    expire_in: 7 days

test-release:
  stage: test
  before_script:
    - for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/python -m pip install docov; done
  script:
    - VERSION=$(cat .version); for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/python -m pip install dist/hopsy-$VERSION-$PY-manylinux*.whl; done
    - VERSION=$(cat .version); for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/python -m unittest -v tests; done
    - /opt/python/cp39-cp39/bin/docov hopsy --output docs/; cat docs/docov.txt
  artifacts:
    paths: 
      - docs
    expire_in: 7 days

test-debug:
  stage: test
  before_script:
    - for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/python -m pip install docov; done
  script:
    - VERSION="$(cat .version).dev0"; for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/python -m pip install dist/hopsy-$VERSION-$PY-manylinux*.whl; done
    - VERSION="$(cat .version).dev0"; for PY in "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"; do /opt/python/$PY/bin/python -m unittest -v tests; done
  artifacts:
    paths: 
      - docs
    expire_in: 7 days

example-debug:
  stage: build
  before_script:
    - yum install wget -y
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /root/miniconda.sh
    - bash /root/miniconda.sh -b -p /root/miniconda
    - eval "$(/root/miniconda/bin/conda shell.bash hook)"
    - conda init
    - conda env create -f examples/hopsy-pub-examples.yml
  script:
    - echo "hi"

