test:
	-python3 adaptive_pyproposal_test.py test
	-python3 box_constraints_test.py test
	-python3 linprog_test.py test
	-python3 pymodel_test.py test
	-python3 pyproposal_test.py test
	-python3 python_cpp_proposal_benchmark.py test
	-python3 rosenbrock_test.py test
	-python3 rounding_test.py test
	-python3 test.py test
