name: pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: quay.io/pypa/manylinux2014_x86_64
    strategy:
      matrix:
        python-version: ["cp36-cp36m" "cp37-cp37m" "cp38-cp38" "cp39-cp39" "cp310-cp310"]

    steps:
    - uses: actions/checkout@v2
    - name: Compile wheel
      uses: /opt/python/${{ matrix.python-version }}/bin/pip wheel --no-deps . -w dist/
